version: "3"

services:
    database:
        image: mariadb
        container_name: "app_db"
        environment:
            MYSQL_ROOT_PASSWORD: "root_password"
            MYSQL_DATABASE: "app_database"
            MYSQL_USER: "database_user"
            MYSQL_PASSWORD: "user_password"
        networks:
            - services

    dbadmin:
        image: phpmyadmin
        container_name: "app_admindb"
        depends_on:
            - database
        environment:
            - PMA_ARBITRARY=1
        networks:
            - services

networks:
    services:
        name: db_network
        driver: bridge
