version: "3"

services:
    database:
        image: mariadb
        container_name: "appdb"
        environment:
            MYSQL_ROOT_PASSWORD: "laravel_db"
            MYSQL_DATABASE: "laravel_db"
            MYSQL_USER: "jupiter"
            MYSQL_PASSWORD: "thebe"
        networks:
            - services

    dbadmin:
        image: phpmyadmin
        container_name: "admindb"
        depends_on:
            - database
        environment:
            - PMA_ARBITRARY=1
        networks:
            - services

networks:
    services:
        name: db_network
        driver: bridge
